### PR TITLE
Convert the project to use maven SDK 2.1.0

### PR DESCRIPTION
**Pull request by iwkse**
Hi,
I've set it up maven to use SDK 2.1.0, it makes testing easier for me.
I've tested against 5.0.d and it works okey.

### CODE REVIEW

**Comment by iwkse** [comment]
There's a bit more of cleanup needed..I just noticed now. I'm closing the pull. Anyway I'd like to have a feedback from you, if you are interested in the changes
Regards,

**Comment by deas** [comment]
To be honest, I don't like the SDK. Generally stopped using it a long time ago. Amongst other things, I don't like amp files for various reasons. I also dislike tomcat which the SDK uses nowadays. In the past, it generally tended to introduce more issues that it solved for me.

**Comment by iwkse** [comment]
Hi, thanks for your reply.
I'm interested in knowing more about your developer chain. I'm new to Alfresco development so I found maven being the best solution because it lets me  load relatively fast Alfresco.
Do you use Jetty? Is it faster than Tomcat? If you can give me some hints and explain a bit more your work chain I will be glad to test it. I was sure there were reasons behind not using SDK and I wanted to know.
Thanks,

**Comment by deas** [comment]
At the end of the day its a fast dev cycle and general convenience I am after. I prefer jetty because it can easily be tweaked in almost any way one could imagine. I dislike amps because they tend to be cumbersome in various ways - during development (tools have no clue about them) and for deployment as well. Some people might have app servers or processes in place that need them - but I don't want to bother with that.  I personally have further with other "alfresco standard" dev-tools. Anyways, I work very very different. You won't find a trace of "my" tooling in the source I have released. In fact it is a bit messy and would require quite a bit explanation. And its moving as well. I am trying to get as close to the Clojure/ClojureScript ecosystem as possible.

**Pull request closed without merging**
